### ISSUE TITLE
How to render a cell to a specific place in a page

### ISSUE THREAD

**Issue by spapas** [intercellular/cell#10]
Hello, one thing I can't really find out from the docs is how to render a cell to a specific place in a page that contains also other stuff. From what I can understand, the cell will be rendered exactly where the component with $cell: true will be found in the DOM. However, I prefer to put my JS scripts at the bottom of the page and not mix'em with the DOM. So I'd like to define a placeholder-div for the cell and instruct it to be rendered there (like how React.render works). Is this possible right now in cell.js?

TIA!

**Comment by gliechtenstein** [comment]
I just added this to the documentation https://github.com/intercellular/tutorial#e-injecting-a-cell-into-an-exsiting-dom-tree Hope it helps! Let me know if you have further questions, thanks!

**Comment by spapas** [comment]
Of course it helps, thank you very much @gliechtenstein !
