### ISSUE TITLE
website stuff

### ISSUE THREAD

**Issue by devsnek** [intercellular/cell#113]
### *.js.org
the people at js.org provide free subdomains for your projects. I thought it might be cool to grab cell.js.org
 https://github.com/js-org/dns.js.org

### Proper CDN with versioning
i think it would be best to serve cell from a versioned cdn `cdn.celljs.org/1.0.0/cell.min.js` perhaps using cdnjs as our main cdn

**Comment by gliechtenstein** [comment]
> *.js.org

I was just looking into this, but looks like we will have to give up on [celljs.org](https://celljs.org) if we want to apply for `cell.js.org` because github allows only one CNAME... Let me know if you know a way around

> Proper CDN with versioning

Great idea, do you know a way to automate this? Or is this something we manually update everytime there's a new release? (been an "avid user" of cdnjs but never really hosted my own library there before 😅) Or even a pointer to how to get this setup would be awesome too. Thanks!

**Comment by devsnek** [comment]
CNAME allows one host per line iirc (i might be wrong)

cdnjs works by having a *friggin huge* github repo with every version of every lib they host, and updates are just prs. This could be automated with travis.

**Comment by devsnek** [comment]
@gliechtenstein could you tag a release sometime in the near future so cdnjs's auto update can run when they merge the pr

**Comment by gliechtenstein** [comment]
Wow totally missed that entire cdnjs thread and just saw it, sorry about that. 

I just went ahead and created a release from `master` branch https://github.com/intercellular/cell/releases/tag/v1.0.0

This would work right?

**Comment by devsnek** [comment]
@gliechtenstein https://cdnjs.cloudflare.com/ajax/libs/cell/1.0.0/cell.min.js 🎉

**Comment by gliechtenstein** [comment]
@devsnek Awesome! Thanks! 🔥🔥🔥

I'll close this since the cdnjs issue is taken care of and there's not much we can do about the CNAME thing at the moment. I guess we can revisit if something changes or there's a way to do this without giving up on the main domain :)

**Comment by devsnek** [comment]
@gliechtenstein i was thinking perhaps the links everywhere that go to celljs.org/cell.min.js should be changed to cdnjs links and also the cell.min.js should be removed from the develop branch

**Comment by gliechtenstein** [comment]
@devsnek done and done and done 👍 

- Switched out the celljs link from the tutorial repo https://github.com/intercellular/tutorial/commit/70c90efe9f328147be075f7d4fa30081e79a73e6
- Updated all existing code from [play.celljs.org](https://play.celljs.org)
- Removed cell.min.js from `develop`: https://github.com/intercellular/cell/commit/b1e8437b0e01c4323d52f1108bb9f65171388a59
