### ISSUE TITLE
'Github' typo in README.md (all branches)

### ISSUE THREAD

**Issue by 0joshuaolson1** [intercellular/cell#117]
-> GitHub

**Comment by gliechtenstein** [comment]
Thanks for reporting! Please feel free to send a pull request, any contribution is welcome! :)

**Comment by gliechtenstein** [comment]
https://github.com/intercellular/cell/commit/41faf5e03eb42fceb4e99a7802fb80985daa6b62

**Comment by gliechtenstein** [comment]
For future reference, editing the README (or any other file) is as easy as going to the edit view https://github.com/intercellular/cell/edit/develop/README.md (in case of readme), updating, and sending a pull request.

Don't worry about messing up, since pull requests need to be merged in anyway :)

**Comment by 0joshuaolson1** [comment]
I would've, but there's still the plan and gh-pages branches. Can you use 1 PR to patch both?

**Comment by gliechtenstein** [comment]
I just merged them all so they're reflected there as well :) You can see here:

https://github.com/intercellular/cell/tree/master

https://github.com/intercellular/cell/tree/gh-pages

You don't have to worry about master and gh-pages branch, when sending a PR, just need to fix `develop` and it will eventually be merged into `master` and `gh-pages`, hope this makes sense!

**Comment by piranna** [comment]
Is `gh-pages` branch pick from master? If it's so, then you can go to project settings and set `master` branch to generate the Github page site, and also configure to only generate it from the `docs` folders... There's no need to have `master` duplicated on `gh-pages` branch.

**Comment by gliechtenstein** [comment]
@piranna yeah currently the website is not generated from a static site generator but I generate it dynamically using an in-house library I wrote. I've been meaning to take care of this at some point but just kept it this way till now. Will think about this and take care of it soon. Thanks for the tip!
