### ISSUE TITLE
Question about instantiation

### ISSUE THREAD

**Issue by piranna** [intercellular/cell#119]
On all the examples I've found so far, a JSON-like object is assigned to a variable at the global context, being only identified by having a `$cell: true` attribute. Does it get "automagically" fetch and used? How? Shouldn't it be better to be set explicitly passing it as a parameter to a function call? Why was it done this way?

**Comment by devsnek** [comment]
it iterates through `Object.keys` on the root (usually `window`)

for more info on why this was the chosen behavior check out #111

**Comment by gliechtenstein** [comment]
check out my new post on this https://github.com/intercellular/cell/issues/125

**Comment by gliechtenstein** [comment]
Closing this, let's continue the discussion at #125
