### ISSUE TITLE
List third-party components

### ISSUE THREAD

**Issue by piranna** [intercellular/cell#120]
`cell` architecture is great and very simple to use, but maybe it's a bit low level. It makes easy to be modular, so what about adding a list of already known cell-based components like the traditional ScroolView and similar ones, so others can go and use them directly of the selves instead of need to craft them from scratch using HTML? Or maybe propose that cell-based components use the `cell-*` prefix on npm, or maybe do both things (list and prefix)?

**Comment by spyhole** [comment]
google material design components +1

**Comment by Caffeinix** [comment]
@spyhole You could probably do something like this pretty easily using Cell and Material Design Lite (https://getmdl.io/).

**Comment by spyhole** [comment]
@Caffeinix yeah, i mean the "mdl" has been merged in to "mdc" (https://github.com/material-components/material-components-web) by Google in https://material.io/

**Comment by gliechtenstein** [comment]
closing with https://github.com/intercellular/cell/issues/130
