### ISSUE TITLE
Probably not a cell issue..

### ISSUE THREAD

**Issue by idkjs** [intercellular/cell#128]
Hi @gliechtenstein. Any idea why this graphql query result is not coming back into celljs. The demo I did before didnt have search in it. I added search and somehow I cant get the return to come back. It looks like its an async issue maybe. Can you take a look at these gists and see if anything pops out to you? This is the [index.html](https://gist.github.com/idkjs/ccc5ea0115491b53cca432ca03c3e240) gist.
this is the  [index.js](https://gist.github.com/idkjs/afc901360dd8d8836228eb0bb1e61cab) gist.

Server is in cloud so you should be able to run it. You will notice in the console that the queries come back both for load and search.  Any additional, random programming advice you feel like you can give, go right ahead.

Thanks.

**Comment by gliechtenstein** [comment]
@idkjs I'm not sure what the contents of `bundle.js` is so it's not easy to see what's going on.

Could you put it on jsfiddle or codepen or jsbin or something like that, so that it can be tried out?

**Comment by gliechtenstein** [comment]
Closing but feel free to comment if you have any updates or questions!

**Comment by idkjs** [comment]
[Bundle.js Gist](https://gist.github.com/idkjs/b3b6c89275e3efe64052209584ea4ee4)
