### ISSUE TITLE
Awesome Cell

### ISSUE THREAD

**Issue by gliechtenstein** [intercellular/cell#130]
Related to https://github.com/intercellular/cell/issues/120

Set up a github page for sharing example code, tutorials, ideas, simple gists, or whatever cell related that's awesome

**Comment by Terrib1e** [comment]
<p>I think this is a great idea. If anyone wants assistance working on something like this I'd love to help.</p>
 <p>   In the meantime, I wanted to share this gist::<a href="https://gist.github.com/Terrib1e/b1e884c4e58efc911a3e8e146664fb1e">Side Nav Bar</a> . It's a  hidden side bar that uses CSS that I converted into Cell. I know most of the magic is in the CSS, but I still think it's cool.</p>
<p> Originally I tried making a function to write the lists and the spans the way you did in the App is Data example on the homepage, but for some reason I couldn't get it to work right. Anyways, keep up the great work! </p>

**Comment by israelroldan** [comment]
Done https://github.com/intercellular/awesome-cell
