### ISSUE TITLE
Make UI from json with cell dynamically

### ISSUE THREAD

**Issue by spyhole** [intercellular/cell#132]

**Comment by gliechtenstein** [comment]
Can you clarify the question? Cell's job already is creating UI from JSON...

**Comment by spyhole** [comment]
👍 I'll to find the code.
i just use cell as front with json from backend api.

**Comment by gliechtenstein** [comment]
I'll close this for now since I feel like you've figured this out, but feel free to comment or reopen if you still have a problem.

**Comment by spyhole** [comment]
found it. https://play.celljs.org/items/gD4fag/edit
thx, @gliechtenstein
