### ISSUE TITLE
deprecated message

### ISSUE THREAD

**Issue by aaronrocha** [intercellular/cell#134]
cell.js:356 [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
(anonymous)	@	cell.js:356
detect	@	cell.js:354
create	@	cell.js:379
(anonymous)	@	cell.js:404

**Comment by gliechtenstein** [comment]
This is related to https://github.com/intercellular/cell/issues/122 and not a real problem, but it keeps coming up and is kind of annoying to see that warning message every time, so I just got rid of it. Please try the latest `develop` branch.

**Comment by aaronrocha** [comment]
thanks
