### ISSUE TITLE
Development Moved to https://github.com/jasonelle/jasonelle

### ISSUE THREAD

**Issue by clsource** [intercellular/cell#184]
https://github.com/jasonelle/jasonelle
will continue Cell legacy. Issues and pull request would be slowly tackled in the other repo

**Comment by clsource** [comment]
Development stopped by Jasonelle in order to focus on Mobile Apps. I recommend using another framework like https://mithril.js.org/index.html or if you want to continue development please let me know. thanks.

**Comment by majormittens** [comment]
I will attempt to create more complex apps with this and might be willing to continue development in the event that it's successful and/or further insight reveals itself.
