### ISSUE TITLE
Uncaught TypeError: Cannot read property '$type' of undefined (in Membrane.build)

### ISSUE THREAD

**Issue by devsnek** [intercellular/cell#27]
Something causes Gene.diff to create a diff with an undefined item, which causes errors when building a new Membrane because reading `$type` of undefined.

The fix I specify below is probably not the right thing to do because of the way the error is triggered (see below). __The addition of the `$update` function__ and __the root cell being `body`__ are what specifically cause this error to happen.

Code to repro:
```js
window.app = {
  $cell: true,
  $type: 'body',
  $components: [
    { $type: 'div', $update: function() {} },
  ],
};
```

My current fix:
```diff
diff --git a/cell.js b/cell.js
index b4d1e3b..ee02462 100644
--- a/cell.js
+++ b/cell.js
@@ -105,7 +105,7 @@
       var plus = _new.map(function(item, index) {
         return { item: item, index: index }
       }).filter(function(item, index) {
-        return new_common.indexOf(index) === -1
+        return item.item && new_common.indexOf(index) === -1
       })
       return { "-" : minus, "+": plus }
     }
```

**Comment by gliechtenstein** [comment]
Hi, I tried the code above but couldn't replicate the error. Could you share a full HTML? That would be helpful for debugging.

**Comment by gliechtenstein** [comment]
Actually, i've been taking a possibly related problem this morning, which occurs when injecting into an existing element (such as `body`). [This](https://github.com/intercellular/cell/commit/3ed08cfda7e24b5672ff667ad926147d1da24059) was the fix, I'm not sure if this would help fix your case, but please do try out the latest update from the develop branch and see if that fixes the problem.

thank you!

**Comment by devsnek** [comment]
this appears to have fixed it, closing for now
