### ISSUE TITLE
$update do not gets executed automatically in window.setTimeout()

### ISSUE THREAD

**Issue by bytethinker** [intercellular/cell#3]
<link rel='stylesheet' type='text/css' href='http://tools.oschina.net/js/syntaxhighlighter_3.0.83/styles/shCoreDefault.css'/><div id="highlighter_593086" class="syntaxhighlighter  js"><div class="toolbar"><span><a href="#" class="toolbar_item command_help help">?</a></span></div><table border="0" cellpadding="0" cellspacing="0"><tbody><tr><td class="gutter"><div class="line number1 index0 alt2">1</div><div class="line number2 index1 alt1">2</div><div class="line number3 index2 alt2">3</div><div class="line number4 index3 alt1">4</div><div class="line number5 index4 alt2">5</div><div class="line number6 index5 alt1">6</div><div class="line number7 index6 alt2">7</div><div class="line number8 index7 alt1">8</div><div class="line number9 index8 alt2">9</div><div class="line number10 index9 alt1">10</div><div class="line number11 index10 alt2">11</div><div class="line number12 index11 alt1">12</div><div class="line number13 index12 alt2">13</div><div class="line number14 index13 alt1">14</div><div class="line number15 index14 alt2">15</div><div class="line number16 index15 alt1">16</div><div class="line number17 index16 alt2">17</div><div class="line number18 index17 alt1">18</div><div class="line number19 index18 alt2">19</div><div class="line number20 index19 alt1">20</div><div class="line number21 index20 alt2">21</div><div class="line number22 index21 alt1">22</div><div class="line number23 index22 alt2">23</div><div class="line number24 index23 alt1">24</div><div class="line number25 index24 alt2">25</div><div class="line number26 index25 alt1">26</div><div class="line number27 index26 alt2">27</div><div class="line number28 index27 alt1">28</div><div class="line number29 index28 alt2">29</div><div class="line number30 index29 alt1">30</div></td><td class="code"><div class="container"><div class="line number1 index0 alt2"><code class="js plain">&lt;html&gt;</code></div><div class="line number2 index1 alt1"><code class="js plain">&lt;meta&nbsp;name=</code><code class="js string">"viewport"</code>&nbsp;<code class="js plain">content=</code><code class="js string">"width=device-width,&nbsp;initial-scale=1"</code><code class="js plain">&gt;</code></div><div class="line number3 index2 alt2"><code class="js plain">&lt;script&nbsp;src=</code><code class="js string">"<a href="https://www.celljs.org/cell.js">https://www.celljs.org/cell.js</a>"</code><code class="js plain">&gt;&lt;/script&gt;</code></div><div class="line number4 index3 alt1"><code class="js plain">&lt;script&nbsp;src=</code><code class="js string">"<a href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js</a>"</code><code class="js plain">&gt;&lt;/script&gt;</code></div><div class="line number5 index4 alt2"><code class="js plain">&lt;script&nbsp;src=</code><code class="js string">"<a href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js">https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js</a>"</code><code class="js plain">&gt;&lt;/script&gt;</code></div><div class="line number6 index5 alt1"><code class="js plain">&lt;link&nbsp;href=</code><code class="js string">"<a href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css</a>"</code>&nbsp;<code class="js plain">rel=</code><code class="js string">"stylesheet"</code><code class="js plain">&gt;</code></div><div class="line number7 index6 alt2"><code class="js plain">&lt;script&gt;</code></div><div class="line number8 index7 alt1"><code class="js keyword">var</code>&nbsp;<code class="js plain">GithubApp&nbsp;=&nbsp;{</code></div><div class="line number9 index8 alt2"><code class="js spaces">&nbsp;&nbsp;</code><code class="js plain">$cell:&nbsp;</code><code class="js keyword">true</code><code class="js plain">,</code></div><div class="line number10 index9 alt1"><code class="js spaces">&nbsp;&nbsp;</code><code class="js plain">_items:&nbsp;[{tag:</code><code class="js string">'bbbb'</code><code class="js plain">}],</code></div><div class="line number11 index10 alt2"><code class="js spaces">&nbsp;&nbsp;</code><code class="js plain">$init:&nbsp;</code><code class="js keyword">function</code><code class="js plain">(){</code></div><div class="line number12 index11 alt1"><code class="js spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="js keyword">var</code>&nbsp;<code class="js plain">self&nbsp;=&nbsp;</code><code class="js keyword">this</code><code class="js plain">;</code></div><div class="line number13 index12 alt2"><code class="js spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="js plain">window.setTimeout(</code><code class="js keyword">function</code><code class="js plain">()</code></div><div class="line number14 index13 alt1"><code class="js spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="js plain">{</code></div><div class="line number15 index14 alt2"><code class="js spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="js plain">self._items&nbsp;=&nbsp;[{tag:</code><code class="js string">'aaaaa'</code><code class="js plain">}];&nbsp;&nbsp;</code><code class="js comments">//$update&nbsp;do&nbsp;not&nbsp;gets&nbsp;executed&nbsp;automatically</code></div><div class="line number16 index15 alt1"><code class="js spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="js plain">},2000);</code></div><div class="line number17 index16 alt2"><code class="js spaces">&nbsp;&nbsp;</code><code class="js plain">},</code></div><div class="line number18 index17 alt1"><code class="js spaces">&nbsp;&nbsp;</code><code class="js plain">_template:&nbsp;</code><code class="js keyword">function</code><code class="js plain">(item){</code></div><div class="line number19 index18 alt2"><code class="js spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="js keyword">return</code>&nbsp;<code class="js plain">{</code></div><div class="line number20 index19 alt1"><code class="js spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="js plain">$components:&nbsp;[{</code></div><div class="line number21 index20 alt2"><code class="js spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="js plain">$text:&nbsp;item.tag</code></div><div class="line number22 index21 alt1"><code class="js spaces">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="js plain">}]</code></div><div class="line number23 index22 alt2"><code class="js spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="js plain">};</code></div><div class="line number24 index23 alt1"><code class="js spaces">&nbsp;&nbsp;</code><code class="js plain">},</code></div><div class="line number25 index24 alt2"><code class="js spaces">&nbsp;&nbsp;</code><code class="js plain">$update:&nbsp;</code><code class="js keyword">function</code><code class="js plain">(){</code></div><div class="line number26 index25 alt1"><code class="js spaces">&nbsp;&nbsp;&nbsp;&nbsp;</code><code class="js keyword">this</code><code class="js plain">.$components&nbsp;=&nbsp;</code><code class="js keyword">this</code><code class="js plain">._items.map(</code><code class="js keyword">this</code><code class="js plain">._template);</code></div><div class="line number27 index26 alt2"><code class="js spaces">&nbsp;&nbsp;</code><code class="js plain">}</code></div><div class="line number28 index27 alt1"><code class="js plain">}</code></div><div class="line number29 index28 alt2"><code class="js plain">&lt;/script&gt;</code></div><div class="line number30 index29 alt1"><code class="js plain">&lt;/html&gt;</code></div></div></td></tr></tbody></table></div>

**Comment by gliechtenstein** [comment]
Thanks for asking. This is probably the only gotcha when it comes to how contexts get resolved on Cell, so I'm happy to answer.

There's one thing to remember about how `_` variables trigger the `$update()` function.

They need to be triggered inside a function that's directly attached on the element context. Let me explain what this means.

When you do:

```
$init: function(){
  this._items = [{tag: "aaaa"}];
}
```

That will trigger an `$update()` automatically.

However if you do 

```
$init: function(){
  var self = this;
  setTimeout(function(){
    self._items = [{tag: "aaaa"}];
  }, 2000)
}
```

That won't trigger `$update()` because the mutation is happening inside the `setTiemout`'s anonymous callback function (and this callback function doesn't exist on the element's context, it's just a parameter passed to `setTimeout`).

So to make this work, we need to make sure the mutation logic happens directly inside a function that's attached to the element context, like this:

```
$init: function(){
  var self = this;
  setTimeout(function() {
    self._refresh([{tag: 'aaaa'}]);
  },2000);
},
_refresh: function(items){
  this._items = items;
},
```

Note how we've created a separate `_refresh` function, and calling it from `setTmeout`. This time it works because the mutation `this._items = items` is happening inside the `_refresh()` function, which is directly tied to the element's context.

The End result:

```html
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="https://www.celljs.org/cell.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">
<script>
var GithubApp = {
  $cell: true,
  _items: [{tag:'bbbb'}],
  $init: function(){
    var self = this;
    window.setTimeout(function()
    {
      self._refresh([{tag: 'aaaa'}]);
    },2000);
  },
  _refresh: function(items){
    this._items = items;
  },
  _template: function(item){
    return {
      $components: [{
        $text: item.tag
      }]
    };
  },
  $update: function(){
    this.$components = this._items.map(this._template);
  }
}
</script>
</html>
```

Hope this makes sense, please let me know if you have further questions!

**Comment by bytethinker** [comment]
OK，thank you for writing up such a detailed reply!
Keep up the great idea!!
