### ISSUE TITLE
[Possible bug?] Out of sync in input demo

### ISSUE THREAD

**Issue by bigopon** [intercellular/cell#30]
In this demo https://play.celljs.org/items/O4Mf6y/edit

If you Input something then delete all text in input field
You will see that the display out of sync

**Comment by gliechtenstein** [comment]
Thanks for reporting! I think this should be fixed with https://github.com/intercellular/cell/commit/3ed08cfda7e24b5672ff667ad926147d1da24059 

Could you try the version on develop branch and let me know if that works? (it should)

Thanks!

**Comment by gliechtenstein** [comment]
Fixed and confirmed here https://github.com/intercellular/cell/issues/20 so closing. Please reopen if it still doesn't work. Thanks!
