### ISSUE TITLE
[Bug?] this.class cannot set class

### ISSUE THREAD

**Issue by almonk** [intercellular/cell#35]
With the following code I cannot set the class of the button:

```
{
    $type: 'button',
    $text: 'Send message',
    $init: function() {
      this.class = "button-primary"
    }
}
```

However, other attributes *do* work like this, for e.g.:

```
{
    $type: 'button',
    $text: 'Send message',
    $init: function() {
      this.disabled = true
    }
}
```

**Comment by devsnek** [comment]
try `className` as per spec

**Comment by almonk** [comment]
@devsnek where is this spec?

**Comment by devsnek** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Element/className

**Comment by almonk** [comment]
@devsnek this fixed it ! thanks
